<?php $helperData = $this->helper('Magecomp\Recaptcha\Helper\Data'); ?>
<div class="block newsletter">
    <div class="title"><strong><?php echo __('Newsletter') ?></strong></div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?php /* @escapeNotVerified */
              echo $block->getFormActionUrl(); ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span>
          <?php /* @escapeNotVerified */
          echo __('Sign Up for Our Newsletter:') ?>
          </span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                           placeholder="<?php /* @escapeNotVerified */
                           echo __('Enter your email address') ?>"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="captcha" style="margin:10px 0px">
                    <div class="g-recaptcha-response-news" id="g-recaptcha-response-news"
                         data-theme="<?php echo $helperData->getThemeOption1(); ?>"
                         data-sitekey="<?php echo $helperData->getSiteKey(); ?>"></div>
                    <div id="g_recaptcha-error-news" style="display: none; color: #e02b27; font-size: 1.2rem;"
                         generated="true"> <?php echo __('This is a required field.') ?> </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */
                echo __('Subscribe') ?>" type="submit"> <span>
        <?php /* @escapeNotVerified */
        echo __('Subscribe') ?>
        </span></button>
            </div>
        </form>
    </div>
</div>

<script src='https://www.google.com/recaptcha/api.js?onload=reCaptchaCallback&render=explicit&hl=<?php echo $helperData->getLocal() ?>'></script>
<script type="text/javascript">
    var canSubmit = false;
    function reCaptchaVerifyNews(response) {
        if (response) {
            canSubmit = true;
        }
    }
    function reCaptchaCallback() {
        grecaptcha.render('g-recaptcha-response-news', {
            'sitekey': '<?php echo $helperData->getSiteKey(); ?>',
            'callback': reCaptchaVerifyNews,
            'theme': '<?php echo $helperData->getThemeOption1(); ?>'
        });
    }
    document.getElementById('newsletter-validate-detail').addEventListener('submit', function (e) {
        if (!canSubmit) {
            jQuery('#g_recaptcha-error-news').show();
            e.preventDefault();
        }
    });
</script>