<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeBaseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
?>
<?php if (!$block->hasError()) :?>
    <?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
    <ul class="checkout methods items checkout-methods-items">
        <?php foreach ($methods as $method) :?>
            <?php $methodHtml = $block->getMethodHtml($method); ?>
            <?php if (trim($methodHtml) !== '') :?>
                <li class="item"><?= /* @noEscape */ $methodHtml ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        <li class="item">
        	<a target="_blank" href="<?php echo $storeBaseUrl.'security-guarantee/'?>">Security Guarantee</a>
        </li>
    </ul>
<?php endif; ?>
