<?php
/**
 * @author Aitoc Team
 * @copyright Copyright (c) 2020 Aitoc (https://www.aitoc.com)
 * @package Aitoc_Gifts
 */
?>
<div id="rule_generated_coupons_tab">
    <?= /** @var \Aitoc\Gifts\Block\Adminhtml\Rule\Edit\Tab\Coupons $block */
        $block->getChildHtml('rule_generated_coupons_tab_form') ?>
    <?= $block->getChildHtml('rule_generated_coupons_tab_grid') ?>
</div>
<script>
    require([
        'jquery',
        "uiRegistry",
        'Magento_Ui/js/modal/alert',
        'prototype'
    ], function(jQuery, registry, alert) {
        function refreshCouponCodesGrid(grid, gridMassAction, transport) {
            grid.reload();
            gridMassAction.unselectAll();
        }

        function generateCouponCodes(idPrefix, generateUrl, grid) {
            $(idPrefix + 'information_fieldset').removeClassName('ignore-validate');
            var validationResult = $(idPrefix + 'information_fieldset').select('input',
                'select', 'textarea').collect( function(elm) {
                return jQuery.validator.validateElement(elm);
            }).all();
            $(idPrefix + 'information_fieldset').addClassName('ignore-validate');

            if (!validationResult) {
                return;
            }

            var elements = $(idPrefix + 'information_fieldset').select('input', 'select', 'textarea');
            var params = Form.serializeElements(elements, true);
            params.form_key = FORM_KEY;
            if ($$('#'+idPrefix + 'information_fieldset .messages')) {
                $$('#'+idPrefix + 'information_fieldset .messages')[0].update();
            }
            if ($('messages')) {
                $('messages').update();
            }
            var couponCodesGrid = eval(grid);
            new Ajax.Request(generateUrl, {
                parameters :params,
                method :'post',
                onComplete : function (transport, param){
                    var response = false;
                    if (transport && transport.responseText) {
                        try {
                            response = JSON.parse(transport.responseText);
                        } catch (e) {
                            console.warn('An error occured while parsing response');
                        }
                    }

                    if (couponCodesGrid) {
                        couponCodesGrid.reload();
                    }

                    if (response && response.messages) {
                        if ($$('#'+idPrefix + 'information_fieldset .messages')) {
                            $$('#'+idPrefix + 'information_fieldset .messages')[0].update(response.messages);
                        } else if ($('messages')) {
                            $('messages').update(response.messages);
                        }
                    }
                    if (response && response.error) {
                        alert({
                            content: response.error
                        });
                    }
                }
            });
        }

        window.generateCouponCodes = generateCouponCodes;
        window.refreshCouponCodesGrid = refreshCouponCodesGrid;
    });
</script>