<?php 
$searchWidget = [
    'Codazon_Shopbybrandpro/js/brands' => [
        'codazon.searchBrands' => [
            'brandUrl'  => $block->getUrl('brands/index/searchBrands'),
            'noResults' => __('No brand matches your input'),
            'resultsS'   => __('There is %1 result.'),
            'resultsP'   => __('There are %1 results.')
        ]
    ]
];
?>
<div class="brand-container">
	<div class="brand-main">
	    <div class="block">
	        <div class="block-title">
	            <strong class="label"><?= __('All brands') ?></strong>
	            <div class="brand-search-wrap" data-mage-init='<?= json_encode($searchWidget) ?>'>
	                <div class="brand-form" data-role="brand-form">
	                    <label class="search-label"></label>
	                    <input data-role="brand_name" placeholder="<?= __('Search brand here') ?>" type="text" class="input-text search-input" />
	                    <div data-role="list-wrap" class="list-wrap"></div>
	                </div>
	            </div>
	        </div>
	        <div class="block-content"><?= $block->getBrandsHtml(); ?></div>
	    </div>
	</div>
</div>