<div class="captcha" style="margin:10px 0px">
    <div class="g-recaptcha-response" id="g-recaptcha-forgotpassword"
         data-theme="<?php echo $block->getThemeOption(); ?>" data-sitekey="<?php echo $block->getSiteKey(); ?>"></div>
    <div id="g_recaptcha-error" style="display: none; color: #e02b27; font-size: 1.2rem;"
         generated="true"><?php /* @escapeNotVerified */
        echo __('This is a required field.') ?></div>
</div>

<script src='https://www.google.com/recaptcha/api.js?onload=reCaptchaCallbackGeneral&render=explicit&hl=<?php echo $block->getLocal(); ?>'></script>

<script type="text/javascript">
    var forgotSubmit = false;
    function reCaptchaVerifyGeneral(response) {
        if (response) {
            forgotSubmit = true;
        }
    }
    document.forms['form-validate'].addEventListener('submit', function (e) {
        if (!forgotSubmit) {
            jQuery('#g_recaptcha-error').show();
            e.preventDefault();
        }
    })


    function reCaptchaCallbackGeneral() {
        grecaptcha.render('g-recaptcha-forgotpassword', {
            'sitekey': '<?php echo $block->getSiteKey(); ?>',
            'callback': reCaptchaVerifyGeneral,
            'theme': '<?php echo $block->getThemeOption(); ?>'
        });
    }

</script>

